// For Me — data definitions
var FM = FM || {};

// ── Entity types ────────────────────────────────────────────
FM.entityTypes = [
  { id:'individual', label:'Individual', desc:'Personal account for everyday use', icon:'👤', risk:0 },
  { id:'self_employed', label:'Self-Employed', desc:'Freelancer, contractor, sole trader', icon:'💼', risk:0 },
  { id:'company', label:'Company / LLC', desc:'Registered business entity', icon:'🏢', risk:0 },
  { id:'trust', label:'Trust / Foundation', desc:'Trust, foundation, or estate', icon:'🏛️', risk:1 },
  { id:'dao', label:'DAO / Digital Entity', desc:'Decentralized or token-based org', icon:'🔗', risk:2 },
];

// ── Industries ──────────────────────────────────────────────
FM.industries = [
  { id:'tech', label:'Technology / SaaS', risk:0 },
  { id:'consulting', label:'Consulting / Professional Services', risk:0 },
  { id:'ecommerce', label:'E-Commerce / Retail', risk:0 },
  { id:'trade', label:'Import / Export / Trade', risk:1 },
  { id:'realestate', label:'Real Estate / Property', risk:1 },
  { id:'manufacturing', label:'Manufacturing', risk:0 },
  { id:'media', label:'Media / Entertainment', risk:0 },
  { id:'finance', label:'Financial Services (non-crypto)', risk:1 },
  { id:'crypto', label:'Crypto / Web3 / Blockchain', risk:2 },
  { id:'gambling', label:'Gambling / Online Gaming', risk:3 },
  { id:'adult', label:'Adult Content', risk:3 },
  { id:'arms', label:'Arms / Defence', risk:3 },
  { id:'fx', label:'FX Brokerage', risk:2 },
  { id:'affiliate', label:'Affiliate Marketing', risk:2 },
  { id:'nutra', label:'Nutraceuticals / Supplements', risk:2 },
  { id:'family_office', label:'Family Office / Holding', risk:1 },
  { id:'yacht_aircraft', label:'Yacht / Aircraft SPV', risk:1 },
  { id:'fund', label:'Private Fund / Investment Vehicle', risk:1 },
  { id:'ngo', label:'Non-Profit / NGO', risk:0 },
  { id:'other', label:'Other', risk:0 },
];

// ── Staff size bands ────────────────────────────────────────
FM.staffBands = [
  { id:'1', label:'Just me', risk:0 },
  { id:'2-10', label:'2–10', risk:0 },
  { id:'11-50', label:'11–50', risk:0 },
  { id:'51-250', label:'51–250', risk:1 },
  { id:'251+', label:'251+', risk:1 },
];

// ── Volume bands ────────────────────────────────────────────
FM.volumeBands = [
  { id:'under10k', label:'Under $10K / month', risk:0, tier:'Melody' },
  { id:'10k-50k', label:'$10K–$50K / month', risk:0, tier:'Melody → Big Band' },
  { id:'50k-250k', label:'$50K–$250K / month', risk:1, tier:'Big Band' },
  { id:'250k-1m', label:'$250K–$1M / month', risk:1, tier:'Big Band → Orchestra' },
  { id:'over1m', label:'$1M+ / month', risk:2, tier:'Orchestra (40% off)' },
];

// ── Payment methods needed ──────────────────────────────────
FM.paymentNeeds = [
  { id:'bank_in', label:'Receive bank transfers', icon:'🏦', desc:'SWIFT, SEPA inbound' },
  { id:'card_in', label:'Receive card payments', icon:'💳', desc:'Clients pay you by card' },
  { id:'crypto_in', label:'Receive crypto', icon:'₿', desc:'BTC, ETH, USDT, USDC in' },
  { id:'bank_out', label:'Send bank transfers', icon:'📤', desc:'SWIFT, SEPA outbound' },
  { id:'crypto_out', label:'Send crypto', icon:'🔗', desc:'To any external wallet' },
  { id:'swap', label:'Swap currencies & crypto', icon:'🔄', desc:'Instant conversion' },
  { id:'cards', label:'Debit cards', icon:'💳', desc:'Apple Pay / Google Pay' },
  { id:'subaccounts', label:'Sub-accounts', icon:'📂', desc:'Separate wallets per project' },
  { id:'masspay', label:'Mass payouts', icon:'📤', desc:'Pay contractors at scale' },
  { id:'otc', label:'VIP OTC', icon:'💎', desc:'Large-volume crypto swaps' },
];

// ── High-risk flags ─────────────────────────────────────────
FM.highRiskFlags = [
  { id:'crypto_exchange', label:'Crypto exchange / brokerage', surcharge:true },
  { id:'gambling', label:'Online gambling / gaming', surcharge:true },
  { id:'adult', label:'Adult content / entertainment', surcharge:true },
  { id:'arms', label:'Arms / defence (licensed)', surcharge:true },
  { id:'fx', label:'FX brokerage', surcharge:true },
  { id:'affiliate', label:'Affiliate marketing / media buying', surcharge:true },
  { id:'nutra', label:'Nutraceuticals / supplements', surcharge:true },
  { id:'third_party_funds', label:'Handle third-party client funds', risk:2 },
  { id:'msb', label:'Money services / money transmission', risk:2 },
  { id:'pep', label:'Politically Exposed Person (PEP)', risk:2 },
];

// ── Document requirements ───────────────────────────────────
FM.docRequirements = {
  individual: [
    { doc:'Government-issued photo ID', why:'Identity verification (KYC)' },
    { doc:'Proof of address', why:'Residency verification' },
    { doc:'Selfie / liveness check', why:'Matches you to your ID' },
  ],
  self_employed: [
    { doc:'Government-issued photo ID', why:'Identity verification (KYC)' },
    { doc:'Proof of address', why:'Residency verification' },
    { doc:'Selfie / liveness check', why:'Matches you to your ID' },
    { doc:'Business registration or tax ID', why:'Self-employment verification' },
  ],
  company: [
    { doc:'Certificate of incorporation', why:'Company existence verification' },
    { doc:'Register of directors', why:'Who controls the company' },
    { doc:'Register of shareholders (25%+)', why:'UBO identification' },
    { doc:'UBO photo ID + proof of address', why:'Per UBO: identity + residency' },
    { doc:'Business activity description', why:'Nature of business' },
  ],
  trust: [
    { doc:'Trust deed / foundation charter', why:'Legal existence' },
    { doc:'Trustee ID + proof of address', why:'Trustee identity' },
    { doc:'Beneficiary declaration', why:'Who benefits' },
    { doc:'Settlor ID + proof of address', why:'Settlor identity' },
  ],
  dao: [
    { doc:'Governance documentation', why:'How decisions are made' },
    { doc:'Key signers ID + proof of address', why:'Per signer: identity + residency' },
    { doc:'Treasury / multisig setup', why:'How funds are controlled' },
    { doc:'Token holder structure', why:'Ownership / governance distribution' },
  ],
  high_risk_extra: [
    { doc:'Source of funds statement', why:'Where did the money come from?' },
    { doc:'Source of wealth statement', why:'How was wealth accumulated?' },
    { doc:'6 months bank statements', why:'Transaction history verification' },
    { doc:'Business plan or operating model', why:'Understand the business' },
  ],
  crypto_extra: [
    { doc:'Wallet ownership proof', why:'Verify you control the wallet' },
    { doc:'Transaction history (3 months)', why:'On-chain activity review' },
  ],
};

// ── Countries with risk ratings (0=low, 1=medium, 2=high, 3=excluded) ─
FM.countries = [
  { code:'AF', iso3:'AFG', name:'Afghanistan', risk:3 },
  { code:'AL', iso3:'ALB', name:'Albania', risk:0 },
  { code:'DZ', iso3:'DZA', name:'Algeria', risk:1 },
  { code:'AD', iso3:'AND', name:'Andorra', risk:0 },
  { code:'AO', iso3:'AGO', name:'Angola', risk:1 },
  { code:'AG', iso3:'ATG', name:'Antigua and Barbuda', risk:0 },
  { code:'AR', iso3:'ARG', name:'Argentina', risk:1 },
  { code:'AM', iso3:'ARM', name:'Armenia', risk:0 },
  { code:'AU', iso3:'AUS', name:'Australia', risk:0, eu:true },
  { code:'AT', iso3:'AUT', name:'Austria', risk:0, eu:true },
  { code:'AZ', iso3:'AZE', name:'Azerbaijan', risk:0 },
  { code:'BS', iso3:'BHS', name:'Bahamas', risk:0 },
  { code:'BH', iso3:'BHR', name:'Bahrain', risk:0 },
  { code:'BD', iso3:'BGD', name:'Bangladesh', risk:1 },
  { code:'BB', iso3:'BRB', name:'Barbados', risk:0 },
  { code:'BY', iso3:'BLR', name:'Belarus', risk:3 },
  { code:'BE', iso3:'BEL', name:'Belgium', risk:0, eu:true },
  { code:'BZ', iso3:'BLZ', name:'Belize', risk:1 },
  { code:'BJ', iso3:'BEN', name:'Benin', risk:1 },
  { code:'BT', iso3:'BTN', name:'Bhutan', risk:0 },
  { code:'BO', iso3:'BOL', name:'Bolivia', risk:1 },
  { code:'BA', iso3:'BIH', name:'Bosnia and Herzegovina', risk:1 },
  { code:'BW', iso3:'BWA', name:'Botswana', risk:0 },
  { code:'BR', iso3:'BRA', name:'Brazil', risk:1 },
  { code:'BN', iso3:'BRN', name:'Brunei', risk:0 },
  { code:'BG', iso3:'BGR', name:'Bulgaria', risk:0, eu:true },
  { code:'BF', iso3:'BFA', name:'Burkina Faso', risk:1 },
  { code:'BI', iso3:'BDI', name:'Burundi', risk:3 },
  { code:'CV', iso3:'CPV', name:'Cabo Verde', risk:0 },
  { code:'KH', iso3:'KHM', name:'Cambodia', risk:2 },
  { code:'CM', iso3:'CMR', name:'Cameroon', risk:2 },
  { code:'CA', iso3:'CAN', name:'Canada', risk:0, eu:true },
  { code:'CF', iso3:'CAF', name:'Central African Republic', risk:3 },
  { code:'TD', iso3:'TCD', name:'Chad', risk:2 },
  { code:'CL', iso3:'CHL', name:'Chile', risk:0 },
  { code:'CN', iso3:'CHN', name:'China', risk:1 },
  { code:'CO', iso3:'COL', name:'Colombia', risk:1 },
  { code:'KM', iso3:'COM', name:'Comoros', risk:1 },
  { code:'CG', iso3:'COG', name:'Congo', risk:2 },
  { code:'CR', iso3:'CRI', name:'Costa Rica', risk:0 },
  { code:'HR', iso3:'HRV', name:'Croatia', risk:0, eu:true },
  { code:'CU', iso3:'CUB', name:'Cuba', risk:3 },
  { code:'CY', iso3:'CYP', name:'Cyprus', risk:0, eu:true },
  { code:'CZ', iso3:'CZE', name:'Czech Republic', risk:0, eu:true },
  { code:'DK', iso3:'DNK', name:'Denmark', risk:0, eu:true },
  { code:'DJ', iso3:'DJI', name:'Djibouti', risk:1 },
  { code:'DM', iso3:'DMA', name:'Dominica', risk:1 },
  { code:'DO', iso3:'DOM', name:'Dominican Republic', risk:1 },
  { code:'EC', iso3:'ECU', name:'Ecuador', risk:1 },
  { code:'EG', iso3:'EGY', name:'Egypt', risk:1 },
  { code:'SV', iso3:'SLV', name:'El Salvador', risk:1 },
  { code:'GQ', iso3:'GNQ', name:'Equatorial Guinea', risk:2 },
  { code:'ER', iso3:'ERI', name:'Eritrea', risk:2 },
  { code:'EE', iso3:'EST', name:'Estonia', risk:0, eu:true },
  { code:'SZ', iso3:'SWZ', name:'Eswatini', risk:1 },
  { code:'ET', iso3:'ETH', name:'Ethiopia', risk:2 },
  { code:'FJ', iso3:'FJI', name:'Fiji', risk:0 },
  { code:'FI', iso3:'FIN', name:'Finland', risk:0, eu:true },
  { code:'FR', iso3:'FRA', name:'France', risk:0, eu:true },
  { code:'GA', iso3:'GAB', name:'Gabon', risk:1 },
  { code:'GM', iso3:'GMB', name:'Gambia', risk:1 },
  { code:'GE', iso3:'GEO', name:'Georgia', risk:0 },
  { code:'DE', iso3:'DEU', name:'Germany', risk:0, eu:true },
  { code:'GH', iso3:'GHA', name:'Ghana', risk:1 },
  { code:'GR', iso3:'GRC', name:'Greece', risk:0, eu:true },
  { code:'GD', iso3:'GRD', name:'Grenada', risk:0 },
  { code:'GT', iso3:'GTM', name:'Guatemala', risk:1 },
  { code:'GN', iso3:'GIN', name:'Guinea', risk:2 },
  { code:'GW', iso3:'GNB', name:'Guinea-Bissau', risk:2 },
  { code:'GY', iso3:'GUY', name:'Guyana', risk:1 },
  { code:'HT', iso3:'HTI', name:'Haiti', risk:2 },
  { code:'HN', iso3:'HND', name:'Honduras', risk:1 },
  { code:'HK', iso3:'HKG', name:'Hong Kong', risk:0 },
  { code:'HU', iso3:'HUN', name:'Hungary', risk:0, eu:true },
  { code:'IS', iso3:'ISL', name:'Iceland', risk:0 },
  { code:'IN', iso3:'IND', name:'India', risk:1 },
  { code:'ID', iso3:'IDN', name:'Indonesia', risk:1 },
  { code:'IR', iso3:'IRN', name:'Iran', risk:3 },
  { code:'IQ', iso3:'IRQ', name:'Iraq', risk:2 },
  { code:'IE', iso3:'IRL', name:'Ireland', risk:0, eu:true },
  { code:'IL', iso3:'ISR', name:'Israel', risk:0 },
  { code:'IT', iso3:'ITA', name:'Italy', risk:0, eu:true },
  { code:'JM', iso3:'JAM', name:'Jamaica', risk:1 },
  { code:'JP', iso3:'JPN', name:'Japan', risk:0 },
  { code:'JO', iso3:'JOR', name:'Jordan', risk:1 },
  { code:'KZ', iso3:'KAZ', name:'Kazakhstan', risk:1 },
  { code:'KE', iso3:'KEN', name:'Kenya', risk:1 },
  { code:'KI', iso3:'KIR', name:'Kiribati', risk:1 },
  { code:'KP', iso3:'PRK', name:'North Korea', risk:3 },
  { code:'KR', iso3:'KOR', name:'South Korea', risk:0 },
  { code:'KW', iso3:'KWT', name:'Kuwait', risk:0 },
  { code:'KG', iso3:'KGZ', name:'Kyrgyzstan', risk:1 },
  { code:'LA', iso3:'LAO', name:'Laos', risk:2 },
  { code:'LV', iso3:'LVA', name:'Latvia', risk:0, eu:true },
  { code:'LB', iso3:'LBN', name:'Lebanon', risk:2 },
  { code:'LS', iso3:'LSO', name:'Lesotho', risk:1 },
  { code:'LR', iso3:'LBR', name:'Liberia', risk:2 },
  { code:'LY', iso3:'LBY', name:'Libya', risk:3 },
  { code:'LI', iso3:'LIE', name:'Liechtenstein', risk:0 },
  { code:'LT', iso3:'LTU', name:'Lithuania', risk:0, eu:true },
  { code:'LU', iso3:'LUX', name:'Luxembourg', risk:0, eu:true },
  { code:'MO', iso3:'MAC', name:'Macau', risk:1 },
  { code:'MG', iso3:'MDG', name:'Madagascar', risk:1 },
  { code:'MW', iso3:'MWI', name:'Malawi', risk:1 },
  { code:'MY', iso3:'MYS', name:'Malaysia', risk:1 },
  { code:'MV', iso3:'MDV', name:'Maldives', risk:0 },
  { code:'ML', iso3:'MLI', name:'Mali', risk:2 },
  { code:'MT', iso3:'MLT', name:'Malta', risk:0, eu:true },
  { code:'MH', iso3:'MHL', name:'Marshall Islands', risk:0 },
  { code:'MR', iso3:'MRT', name:'Mauritania', risk:2 },
  { code:'MU', iso3:'MUS', name:'Mauritius', risk:0 },
  { code:'MX', iso3:'MEX', name:'Mexico', risk:1 },
  { code:'FM', iso3:'FSM', name:'Micronesia', risk:0 },
  { code:'MD', iso3:'MDA', name:'Moldova', risk:1 },
  { code:'MC', iso3:'MCO', name:'Monaco', risk:0 },
  { code:'MN', iso3:'MNG', name:'Mongolia', risk:1 },
  { code:'ME', iso3:'MNE', name:'Montenegro', risk:1 },
  { code:'MA', iso3:'MAR', name:'Morocco', risk:1 },
  { code:'MZ', iso3:'MOZ', name:'Mozambique', risk:1 },
  { code:'MM', iso3:'MMR', name:'Myanmar', risk:3 },
  { code:'NA', iso3:'NAM', name:'Namibia', risk:1 },
  { code:'NR', iso3:'NRU', name:'Nauru', risk:1 },
  { code:'NP', iso3:'NPL', name:'Nepal', risk:1 },
  { code:'NL', iso3:'NLD', name:'Netherlands', risk:0, eu:true },
  { code:'NZ', iso3:'NZL', name:'New Zealand', risk:0, eu:true },
  { code:'NI', iso3:'NIC', name:'Nicaragua', risk:2 },
  { code:'NE', iso3:'NER', name:'Niger', risk:2 },
  { code:'NG', iso3:'NGA', name:'Nigeria', risk:1 },
  { code:'MK', iso3:'MKD', name:'North Macedonia', risk:1 },
  { code:'NO', iso3:'NOR', name:'Norway', risk:0 },
  { code:'OM', iso3:'OMN', name:'Oman', risk:0 },
  { code:'PK', iso3:'PAK', name:'Pakistan', risk:2 },
  { code:'PW', iso3:'PLW', name:'Palau', risk:0 },
  { code:'PA', iso3:'PAN', name:'Panama', risk:1 },
  { code:'PG', iso3:'PNG', name:'Papua New Guinea', risk:1 },
  { code:'PY', iso3:'PRY', name:'Paraguay', risk:1 },
  { code:'PE', iso3:'PER', name:'Peru', risk:1 },
  { code:'PH', iso3:'PHL', name:'Philippines', risk:1 },
  { code:'PL', iso3:'POL', name:'Poland', risk:0, eu:true },
  { code:'PT', iso3:'PRT', name:'Portugal', risk:0, eu:true },
  { code:'QA', iso3:'QAT', name:'Qatar', risk:0 },
  { code:'RO', iso3:'ROU', name:'Romania', risk:0, eu:true },
  { code:'RU', iso3:'RUS', name:'Russia', risk:3 },
  { code:'RW', iso3:'RWA', name:'Rwanda', risk:0 },
  { code:'KN', iso3:'KNA', name:'Saint Kitts and Nevis', risk:0 },
  { code:'LC', iso3:'LCA', name:'Saint Lucia', risk:0 },
  { code:'VC', iso3:'VCT', name:'Saint Vincent', risk:0 },
  { code:'WS', iso3:'WSM', name:'Samoa', risk:0 },
  { code:'SM', iso3:'SMR', name:'San Marino', risk:0 },
  { code:'ST', iso3:'STP', name:'Sao Tome and Principe', risk:1 },
  { code:'SA', iso3:'SAU', name:'Saudi Arabia', risk:1 },
  { code:'SN', iso3:'SEN', name:'Senegal', risk:1 },
  { code:'RS', iso3:'SRB', name:'Serbia', risk:1 },
  { code:'SC', iso3:'SYC', name:'Seychelles', risk:0 },
  { code:'SL', iso3:'SLE', name:'Sierra Leone', risk:2 },
  { code:'SG', iso3:'SGP', name:'Singapore', risk:0 },
  { code:'SK', iso3:'SVK', name:'Slovakia', risk:0, eu:true },
  { code:'SI', iso3:'SVN', name:'Slovenia', risk:0, eu:true },
  { code:'SB', iso3:'SLB', name:'Solomon Islands', risk:0 },
  { code:'SO', iso3:'SOM', name:'Somalia', risk:3 },
  { code:'ZA', iso3:'ZAF', name:'South Africa', risk:1 },
  { code:'SS', iso3:'SSD', name:'South Sudan', risk:3 },
  { code:'ES', iso3:'ESP', name:'Spain', risk:0, eu:true },
  { code:'LK', iso3:'LKA', name:'Sri Lanka', risk:1 },
  { code:'SD', iso3:'SDN', name:'Sudan', risk:3 },
  { code:'SR', iso3:'SUR', name:'Suriname', risk:1 },
  { code:'SE', iso3:'SWE', name:'Sweden', risk:0, eu:true },
  { code:'CH', iso3:'CHE', name:'Switzerland', risk:0 },
  { code:'SY', iso3:'SYR', name:'Syria', risk:3 },
  { code:'TW', iso3:'TWN', name:'Taiwan', risk:0 },
  { code:'TJ', iso3:'TJK', name:'Tajikistan', risk:1 },
  { code:'TZ', iso3:'TZA', name:'Tanzania', risk:1 },
  { code:'TH', iso3:'THA', name:'Thailand', risk:1 },
  { code:'TL', iso3:'TLS', name:'Timor-Leste', risk:1 },
  { code:'TG', iso3:'TGO', name:'Togo', risk:1 },
  { code:'TO', iso3:'TON', name:'Tonga', risk:0 },
  { code:'TT', iso3:'TTO', name:'Trinidad and Tobago', risk:0 },
  { code:'TN', iso3:'TUN', name:'Tunisia', risk:1 },
  { code:'TR', iso3:'TUR', name:'Turkey', risk:1 },
  { code:'TM', iso3:'TKM', name:'Turkmenistan', risk:2 },
  { code:'TV', iso3:'TUV', name:'Tuvalu', risk:0 },
  { code:'UG', iso3:'UGA', name:'Uganda', risk:1 },
  { code:'UA', iso3:'UKR', name:'Ukraine', risk:1 },
  { code:'AE', iso3:'ARE', name:'United Arab Emirates', risk:0 },
  { code:'GB', iso3:'GBR', name:'United Kingdom', risk:0 },
  { code:'US', iso3:'USA', name:'United States', risk:0, us:true },
  { code:'UY', iso3:'URY', name:'Uruguay', risk:0 },
  { code:'UZ', iso3:'UZB', name:'Uzbekistan', risk:1 },
  { code:'VU', iso3:'VUT', name:'Vanuatu', risk:0 },
  { code:'VA', iso3:'VAT', name:'Vatican City', risk:0 },
  { code:'VE', iso3:'VEN', name:'Venezuela', risk:3 },
  { code:'VN', iso3:'VNM', name:'Vietnam', risk:1 },
  { code:'YE', iso3:'YEM', name:'Yemen', risk:3 },
  { code:'ZM', iso3:'ZMB', name:'Zambia', risk:1 },
  { code:'ZW', iso3:'ZWE', name:'Zimbabwe', risk:2 },
];
